name: ci

on:
  push:
    tags:
      - "*"

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Tag Name
        id: get_tag_name
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -o '[^/]*$')
          echo "::set-output name=tag_name::$tag_name"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORIES }}/go_emqx_exhook:${{ steps.get_tag_name.outputs.tag_name }}
